name: dart_event_bus
description: EventBus for Dart.   
version: 1.0.0
repository: https://github.com/Avataromvatar/dart_event_bus

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
